- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{icinga_server_common_role_tasks_config}}'

- name: Granting adm access to log files
  acl:
    path: "{{item['path']}}"
    entity: adm
    etype: group
    permissions: "{{item['permissions']}}"
    default: "{{item['default']}}"
    state: present
  with_items:
    - { path: '{{icinga_server_effective_log_dir}}', default: False, permissions: rx }
    - { path: '{{icinga_server_cgi_log_dir}}', default: False, permissions: rx }
    - { path: '{{icinga_server_cgi_log_dir}}', default: True, permissions: r }
    - { path: '{{icinga_server_cgi_log_dir}}/icinga.log', default: False, permissions: r }
    - { path: '{{icinga_server_cgi_log_dir}}/icinga-cgi.log', default: False, permissions: r }
    - { path: '{{icinga_server_service_log_dir}}', default: False, permissions: rx }
    - { path: '{{icinga_server_service_log_dir}}', default: True, permissions: r }
    - { path: '{{icinga_server_service_log_dir}}/icinga.log', default: False, permissions: r }
    - { path: '{{icinga_server_service_debug_log_dir}}', default: False, permissions: rx }
    - { path: '{{icinga_server_service_debug_log_dir}}', default: True, permissions: r }
    - { path: '{{icinga_server_service_debug_log_dir}}/icinga-debug.log', default: False, permissions: r }

- name: Granting www-data access to service log files
  acl:
    path: "{{item['path']}}"
    entity: www-data
    etype: user
    permissions: "{{item['permissions']}}"
    default: "{{item['default']}}"
    state: present
  with_items:
    - { path: '{{icinga_server_service_log_dir}}', default: False, permissions: rx }
    - { path: '{{icinga_server_service_log_dir}}', default: True, permissions: r }
    - { path: '{{icinga_server_service_log_dir}}/icinga.log', default: False, permissions: r }
    - { path: '{{icinga_server_service_log_dir}}/archive', default: False, permissions: rx }
    - { path: '{{icinga_server_service_log_dir}}/archive', default: True, permissions: r }

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{icinga_server_common_role_tasks_config}}'

- name: Fixup directory permissions for current install
  file:
    state: directory
    path: '{{icinga_server_command_dir}}'
    owner: nagios
    group: www-data
    mode: 02710

- name: Update Icinga configuration
  template:
    dest: '/etc/icinga/{{item}}.cfg'
    src: '{{item}}.cfg.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - icinga
    - cgi
  notify:
    reload icinga

- name: Drop unused default configuration
  template:
    dest: '/etc/icinga/{{item}}.cfg'
    src: 'refer_to_objects.cfg.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - commands
  notify:
    reload icinga

- name: Drop unused default objects
  file:
    state: absent
    path: '{{icinga_server_object_path}}/{{item}}.cfg'
  with_items:
    - contacts_icinga
    - extinfo_icinga
    - generic-host_icinga
    - generic-service_icinga
    - hostgroups_icinga
    - ido2db_check_proc
    - localhost_icinga
    - services_icinga
    - timeperiods_icinga
  notify:
    reload icinga

- name: Create subdirectories for objects
  file:
    state: directory
    path: '{{icinga_server_object_path}}/{{item}}'
    owner: root
    group: root
    mode: 0555
  with_items:
    - commands
    - hosts
    - services
    - templates
    - virtuals

- name: Update default objects
  template:
    dest: '{{icinga_server_object_path}}/{{item.dir}}/{{item.name}}.cfg'
    src: '{{(item.dir + "_") if item.dir != "." else ""}}{{item.name}}.cfg.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - {dir: 'commands', name: 'check'}
    - {dir: 'commands', name: 'notification'}
    - {dir: 'commands', name: 'performance_data'}
    - {dir: 'templates', name: 'contacts'}
    - {dir: 'templates', name: 'hosts'}
    - {dir: 'templates', name: 'services'}
    - {dir: '.', name: 'contactgroups'}
    - {dir: '.', name: 'timeperiods'}
  notify:
    reload icinga

- name: Prepare notes images
  file:
    state: link
    path: '{{icinga_server_htdocs_dir}}/images/{{item}}-notes.gif'
    src: 'stats.gif'
  with_items:
    - 1
    - 2
    - 3
    - 4


# This and the following definition are only needed to allow Icinga
# to expand hostgroups before the icinga-client role ran on the hosts.
- name: Check if host definitions exist
  stat:
    path: '{{icinga_server_object_path}}/hosts/{{item}}.cfg'
  with_items: '{{groups["all"]}}'
  register: icinga_server_reg_host_def_stats

- name: Generate host icinga config
  template:
    dest: '{{icinga_server_object_path}}/hosts/{{item.item}}-unspecified.cfg'
    src: 'unspecified-host.cfg.j2'
    owner: root
    group: root
    mode: 0444
  with_items: '{{icinga_server_reg_host_def_stats.results}}'
  when: 'item.stat is defined and not item.stat.exists'

- name: Bring helper scripts in place
  template:
    dest: '/etc/icinga/{{item}}.sh'
    src: '{{item}}.sh.j2'
    owner: root
    group: root
    mode: 0544
  with_items:
    update_contacts
  notify:
    reload icinga

- name: Update contacts
  command: /etc/icinga/update_contacts.sh
  register: icinga_server_reg_contacts_update
  notify:
    reload icinga
  changed_when: icinga_server_reg_contacts_update['stdout'] != ''

- name: Generate virtual host icinga config
  template:
    dest: '{{icinga_server_object_path}}/hosts/{{item.item}}.virtual.cfg'
    src: 'virtual-host.cfg.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - item: external-domains
    - item: internal-domains
  notify:
    reload icinga
  tags:
    - 'icinga-client'

- name: Generate virtual host service config
  template:
    dest: '{{icinga_server_object_path}}/virtual-services-{{item["name"]}}.cfg'
    src: 'virtual-services.cfg.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - {name: 'external-domains', domains: '{{monitoring_external_websites}}'}
    - {name: 'internal-domains', domains: '{{monitoring_internal_websites}}'}
  notify:
    reload icinga
  tags:
    - 'icinga-client'

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{icinga_server_common_role_tasks_config}}'
