- name: Drop-out for unsupported distributions in common-role-tasks-package-install
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{common_role_tasks_package_install_parent_role}}' role. Supported are ['Debian']"
  when: "qhost_distribution not in ['Debian']"

- name: '{{common_role_tasks_package_install_parent_role}}: Install packages'
  apt:
    name: "{{common_role_tasks_package_install_config['packages']}}"
    state: present
  when: "common_role_tasks_package_install_config['packages'] is defined"
  notify: "{{common_role_tasks_package_install_config['notifications']}}"
