- name: restart nslcd
  service:
    name: nslcd
    state: restarted

- name: restart nscd
  service:
    name: nscd
    state: restarted

- name: regenerate pam
  command: pam-auth-update --package --enable mkhomedir
  become: true
