- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian"]'

- name: Install common packages
  apt:
    name:
      - atop
      - psmisc # provides pstree
      - net-tools # provides netstat
      - aptitude # Ansible prefers `aptitude` over `apt-get`
    state: present

- name: Ensure uninstalled packages are uninstalled
  apt:
    name:  '{{item}}'
    state: absent
  with_items: []

- name: Enable common package services
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  with_items:
    - atop
