- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{ansible_distribution}}' in '{{role_path|basename}}' role"
  when: 'ansible_distribution not in ["Debian"]'

- name: Set timezone
  timezone:
    name: UTC
