- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian"]'

- name: Add firewall loading script
  template:
    dest: '/etc/network/if-pre-up.d/iptables'
    src: 'iptables-permanent.sh.j2'
    owner: root
    group: root
    mode: 0555

- name: Set up firewall
  template:
    dest: '{{firewall_late_rules_file}}'
    src: 'iptables.rules.j2'
    owner: root
    group: root
    mode: 0444
  notify:
    reload iptables
