graphite_var_lib_dir: /var/lib/graphite
graphite_whisper_dir: /var/lib/graphite/whisper
graphite_log_dir: '/var/log/graphite'
graphite_alternate_log_dir: '/var/log/carbon'

graphite_effective_data_disk: '{{common_directories_default_data_dir}}'
graphite_effective_data_dir: '{{graphite_effective_data_disk}}/graphite'
graphite_effective_var_lib_dir: '{{graphite_effective_data_dir}}/var-lib-graphite'
graphite_effective_whisper_dir: '{{graphite_effective_data_dir}}/whisper'
graphite_effective_log_dir: '{{graphite_effective_data_dir}}/logs'

graphite_database_backend: sqlite3
graphite_database_name: '{{graphite_var_lib_dir}}/graphite.db'
graphite_database_host: ''
graphite_database_port: ''
graphite_database_user: ''
graphite_database_password: ''

graphite_log_level: '{{logging_default_log_level}}'

graphite_line_receiver_port: 2003
graphite_cache_query_port: 7002

graphite_web_net_accesses: []
graphite_receive_net_accesses: []
graphite_query_net_accesses: []

graphite_common_role_tasks_config:
  role: graphite
  supported_distributions:
    - 'Debian'
  user: _graphite
  paths:
    - '{{graphite_effective_data_dir}}'
    - '{{graphite_effective_var_lib_dir}}'
    - '{{graphite_effective_whisper_dir}}'
    - '{{graphite_effective_log_dir}}'
    - {state: link, path: '{{graphite_var_lib_dir}}', source: '{{graphite_effective_var_lib_dir}}'}
    - {state: link, path: '{{graphite_whisper_dir}}', source: '{{graphite_effective_whisper_dir}}'}
    - {state: link, path: '{{graphite_log_dir}}', source: '{{graphite_effective_log_dir}}'}
    - {state: link, path: '{{graphite_alternate_log_dir}}', source: '{{graphite_effective_log_dir}}'}
    - /etc/carbon
    - /etc/graphite
  packages:
    - graphite-web
    - graphite-carbon
    - libapache2-mod-wsgi-py3
  notifications:
    - reload carbon
  port_configs:
    - name: GRAPHITE_LINE_RECEIVER
      port: '{{graphite_line_receiver_port}}'
      incoming_net_accesses: '{{graphite_receive_net_accesses}}'
    - name: GRAPHITE_CACHE
      port: '{{graphite_cache_query_port}}'
      incoming_net_accesses: '{{graphite_query_net_accesses}}'
  services:
    - carbon-cache
  dashboards: []
  dashboard_host_rows:
    - '{{inventory_hostname_short | dashboard_row_graphite}}'
  monitoring_checks:
    - services

graphite_service_users:
  - service-grafana
