# lint:no-logging-needed

- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian"]'

- name: Disable IPv6
  sysctl:
    key: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/20-disable_ipv6.conf
    sysctl_set: yes

- name: Install needed packages
  apt:
    name: resolvconf
    state: present

- name: Stop daemons from messing with /etc/resolv.conf
  template:
    dest: '/etc/resolvconf.conf'
    src: 'resolvconf.conf.j2'
    owner: root
    group: root
    mode: 0444
  notify:
    reload resolvconf

- name: Render proper resolv.conf
  template:
    dest: '/etc/resolv.conf'
    src: 'resolv.conf.j2'
    owner: root
    group: root
    mode: 0444
