vpn_log_dir: '/var/log/openvpn'

vpn_effective_data_disk: '{{common_directories_default_data_dir}}'
vpn_effective_data_dir: '{{vpn_effective_data_disk}}/vpn'
vpn_effective_log_dir: '{{vpn_effective_data_dir}}/logs'

vpn_log_level: '{{logging_default_log_level}}'

vpn_default_heartbeat_rate: 10

vpn_common_role_tasks_config:
  role: vpn
  supported_distributions:
    - 'Debian'
    - 'Gentoo'
  user: omit
  paths:
    - { path: '/etc/openvpn', mode: '400' }
    - '{{vpn_effective_data_dir}}'
    - '{{vpn_effective_log_dir}}'
    - {state: link, path: '{{vpn_log_dir}}', source: '{{vpn_effective_log_dir}}'}
  packages:
    - openvpn
  notifications: []
  port_configs: "{% set collector = ([] | var_shim_init) %}{% for item in (inventory_hostname | host_nets(net_configs, type='vpn'))%}{{collector|var_shim_add([{'port': item['port'], 'name': 'VPN_' ~ (item | net_slug(inventory_hostname)), 'incoming_net_accesses': [{'net_key': 'internet', 'hosts': [item[item | net_host_key('remote', inventory_hostname)]]}]}])}}{% endfor %}{{collector|var_shim_get}}"
  services: []
  log_files: "{% set collector = ([] | var_shim_init) %}{% for item in (inventory_hostname | host_nets(net_configs, type='vpn'))%}{{collector|var_shim_add([{'file': vpn_log_dir + '/' + (item| net_slug(inventory_hostname)) + '.log', 'group': 'vpn', 'item': (item| net_slug(inventory_hostname)), 'description': 'VPN log file for connection to ' + item[item | net_host_key('remote', inventory_hostname)]}])}}{% endfor %}{{collector|var_shim_get}}"
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks: "{% set collector = ([] | var_shim_init) %}{% for item in (inventory_hostname | host_nets(net_configs, type='vpn'))%}{% set slug = (item| net_slug(inventory_hostname)) %}{{collector|var_shim_add([{'name': slug + '/Server', 'command': '/usr/sbin/openvpn', 'argument': '/etc/openvpn/' + slug + '.conf'}, {'name': slug + '/Status', 'type': 'file_age', 'warn': 30, 'critical': 300, 'path': '/run/openvpn/' + slug + '.status'}])}}{% endfor %}{{collector|var_shim_get}}"
