ssh_server_port: 22
ssh_server_net_accesses: '{{inventory_hostname | host_net_keys(net_configs, exclude=["internet"]) | list}}'
ssh_server_log_level: '{{logging_default_log_level}}'

ssh_server_common_role_tasks_config:
  role: ssh-server
  supported_distributions:
    - 'Debian'
  user: omit
  paths:
    - {path: '/etc/ssh', user: root, group: root, mode: '755'}
  packages:
    - openssh-server
  notifications:
    - restart sshd
  port_configs:
    - name: SSH
      port: '{{ssh_server_port}}'
      incoming_net_accesses: '{{ssh_server_net_accesses}}'
  services:
    - ssh
  log_files: []
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks: []
