- import_playbook: rolebooks/common-early.yml

- import_playbook: rolebooks/ldap-servers.yml
- import_playbook: rolebooks/vpn.yml

- import_playbook: rolebooks/mail.yml
- import_playbook: rolebooks/graphite.yml
- import_playbook: rolebooks/grafana.yml

- import_playbook: rolebooks/local.yml
- import_playbook: rolebooks/icinga-servers.yml

- import_playbook: rolebooks/common-late.yml
