smtp_server_port: 25
smtp_server_localpart_lists: {}
smtp_server_domain_lists: {}
smtp_server_local_domains: []
smtp_server_log_level: '{{logging_default_log_level}}'
smtp_server_relay_domains_from_host: {}
smtp_server_alias_files: '{{smtp_server_alias_files_defaults | update_dict(smtp_server_alias_files_extra)}}'
smtp_server_alias_files_defaults:
  '':
    operator:
      - MAILER-DAEMON
      - abuse
      - adm
      - bin
      - daemon
      - dmarc
      - exim
      - ftp
      - hostmaster
      - lp
      - mail
      - named
      - news
      - nobody
      - noc
      - postfix
      - postmaster
      - root
      - security
      - usenet
      - uucp
      - webmaster
      - www
    '/dev/null':
      - 'decode'
    '{{effective_sysadmin_email_address_local_part}}':
      - 'operator'
smtp_server_alias_files_extra: {}
smtp_server_dkim_domains: []
smtp_server_routers: {}
smtp_server_port_ssl_config: compat
smtp_server_extra_port_ssl_config: hardened

smtp_server_relay_net_accesses_defaults:
  - loopback
smtp_server_relay_net_accesses_extra: []
smtp_server_relay_net_accesses: '{{(smtp_server_relay_net_accesses_defaults + smtp_server_relay_net_accesses_extra)}}'
smtp_server_net_accesses_defaults: '{{smtp_server_relay_net_accesses}}'
smtp_server_net_accesses_extra: []
smtp_server_net_accesses: '{{(smtp_server_net_accesses_defaults + smtp_server_net_accesses_extra)}}'

smtp_server_common_role_tasks_config:
  role: smtp-server
  supported_distributions:
    - 'Debian'
  user: Debian-exim
  extra_groups:
    - ssl-cert
  paths:
    - { path: '/etc/exim4', user: root, group: root, mode: '555' }
    - { path: '/etc/exim4/dkim', user: root, group: root, mode: '555' }
    - { path: '/etc/mail', user: root, group: root, mode: '555' }
  packages:
    - exim4-daemon-heavy
  notifications:
    - reload exim
  port_configs:
    - name: SMTP
      port: '{{smtp_server_port}}'
      incoming_net_accesses: '{{smtp_server_net_accesses}}'
  services:
    - exim4
  log_files: []
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks:
    - {'name': 'Daemon', command: 'exim4', user: 'Debian-exim'}
