# qa:lint:distribution-independent
# qa:lint:no-log-level-needed

- name: Explicitizing log file config
  set_fact:
    logging_log_files: '{{logging_log_files | logging_expand_log_files}}'
  changed_when: False
  tags:
    - always

- name: Explicitizing monitoring check config
  set_fact:
    monitoring_check_config: '{{monitoring_check_config | monitoring_checks_explicitize}}'
  changed_when: False
  tags:
    - always

- name: Explicitizing dashboard configs
  set_fact:
    dashboards: '{{dashboards + [dashboard_host | dashboard_add_rows(dashboard_host_rows)]}}'
  changed_when: False
  tags:
    - always
