# qa:lint:distribution-independent
# lint:no-logging-needed

- name: '{{common_role_tasks_end_parent_role}}: Ensure services are up and running'
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  with_items: "{{common_role_tasks_end_config['services']}}"

- name: '{{common_role_tasks_end_parent_role}}: Add dashboards'
  set_fact:
    dashboards: "{{dashboards + common_role_tasks_end_config['dashboards']}}"
  changed_when: False
  tags:
    - always

- name: '{{common_role_tasks_end_parent_role}}: Add dashboard rows'
  set_fact:
    dashboard_host_rows: "{{dashboard_host_rows + common_role_tasks_end_config['dashboard_host_rows']}}"
  changed_when: False
  tags:
    - always

- name: '{{common_role_tasks_end_parent_role}}: Updating firewall port config'
  set_fact:
    firewall_late_port_config: '{{firewall_late_port_config | default({}) | update_dict({
      item["port"]: {
        "name": item["name"],
        "protocol": (item["protocol"] | default("tcp")),
        "incoming_net_accesses": item["incoming_net_accesses"],
      }
    }, merge_lists=True)}}'
  changed_when: False
  with_items: "{{common_role_tasks_end_config['port_configs']}}"
  tags:
    - always

- name: '{{common_role_tasks_end_parent_role}}: Updating monitoring config'
  set_fact:
    monitoring_check_config: '{{monitoring_check_config | monitoring_checks_append_common_role_tasks_config(common_role_tasks_end_config)}}'
  changed_when: False
  tags:
    - always
