# lint-distribution-independent

- name: '{{common_role_tasks_end_parent_role}}: Updating firewall port config'
  set_fact:
    firewall_late_port_config: '{{firewall_late_port_config | default({}) | update_dict({
      item["port"]: {
        "name": item["name"],
        "protocol": (item["protocol"] | default("tcp")),
        "incoming_net_accesses": (item["incoming_net_accesses"] | default([])),
      }
    }, merge_lists=True)}}'
  changed_when: False
  with_items: "{{common_role_tasks_end_config['port_configs'] | default([])}}"
  tags:
    - always
