# qa:lint:distribution-independent
# qa:lint:no-log-level-needed

- name: '{{common_role_tasks_end_parent_role}}: Ensure services are up and running'
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  with_items: "{{common_role_tasks_end_config['services']}}"

- name: '{{common_role_tasks_end_parent_role}}: Add dashboards'
  set_fact:
    dashboards: "{{dashboards + common_role_tasks_end_config['dashboards']}}"
  changed_when: False
  tags:
    - always

- name: '{{common_role_tasks_end_parent_role}}: Add dashboard rows'
  set_fact:
    dashboard_host_rows: "{{dashboard_host_rows + common_role_tasks_end_config['dashboard_host_rows']}}"
  changed_when: False
  tags:
    - always

- name: '{{common_role_tasks_end_parent_role}}: Updating firewall port config'
  set_fact:
    firewall_late_port_config: '{{firewall_late_port_config | default({}) | update_dict({
      (None if (item["protocol"] | default("tcp")) == "icmp" else item["port"]): {
        "name": item["name"],
        "protocol": (item["protocol"] | default("tcp")),
        "icmp-type": (item["icmp_type"] | default(omit)),
        "incoming_net_accesses": item["incoming_net_accesses"],
      }
    }, merge_lists=True)}}'
  changed_when: False
  with_items: "{{common_role_tasks_end_config['port_configs']}}"
  tags:
    - always

- name: '{{common_role_tasks_end_parent_role}}: Updating monitoring config'
  set_fact:
    monitoring_check_config: '{{monitoring_check_config | monitoring_checks_append_common_role_tasks_config(common_role_tasks_end_config)}}'
  changed_when: False
  tags:
    - always

- name: '{{common_role_tasks_end_parent_role}}: Update log file config'
  set_fact:
    logging_log_files: "{{logging_log_files + (common_role_tasks_end_config['log_files'] | logging_expand_log_files_for_common_task_rules(common_role_tasks_end_config))}}"
  changed_when: False
  tags:
    - always
