apache_website_domain: None
apache_website_locations: []
apache_website_htpasswds: {}
apache_website_is_https: True
apache_website_log_anonymously: True
apache_website_log_level: '{{apache_webserver_log_level}}'
apache_website_net_accesses:
  - loopback
apache_website_add_www_redirects: '{{(apache_website_domain | split(".") | length) < 3}}'
apache_website_redirects: []
apache_website_rewrites: []
apache_website_mod_configs: {}

apache_website_common_role_tasks_config:
  role: 'apache-website ({{apache_website_domain}})'
  supported_distributions:
    - 'Debian/buster'
  user: omit
  paths:
    - '{{apache_webserver_effective_data_dir}}'
    - '{{apache_webserver_effective_log_dir}}'
    - /etc/apache2
    - /etc/apache2/sites-available
    - /etc/apache2/sites-enabled
    - state: link
      path: '/etc/apache2/sites-available/{{apache_website_domain}}.conf'
      source: '{{web_site_root_dir}}/{{apache_website_domain}}/conf/{{apache_website_domain}}.conf'
      force: yes
    - state: link
      path: '/etc/apache2/sites-enabled/{{"00-" if apache_website_domain == "default" else ""}}{{apache_website_domain}}.conf'
      source: '/etc/apache2/sites-available/{{apache_website_domain}}.conf'
      force: yes
    - {state: link, path: '{{apache_webserver_effective_log_dir}}/{{apache_website_domain}}', source: '{{web_site_root_dir}}/{{apache_website_domain}}/logs'}
  packages: []
  notifications:
    - 'mark webserver config changed'
  port_configs: []
  services: []
  log_files: [] # TO-DO: Configure logging
  dashboards: []
  dashboard_host_rows: "{{inventory_hostname_short | dashboard_rows_website('apache', apache_website_domain)}}"
  monitoring_checks:
    - {type: 'website', domain: '{{apache_website_domain}}', kind: 'apache'}
