apache_website_domain: None
apache_website_locations: []
apache_website_htpasswds: {}
apache_website_is_https: True
apache_website_log_anonymously: True
apache_website_net_accesses:
  - loopback
apache_website_add_www_redirects: '{{(apache_website_domain | split(".") | length) < 3}}'
apache_website_redirects: []
apache_website_rewrites: []
apache_website_mod_configs: {}

apache_website_common_role_tasks_config:
  role: 'apache-website ({{apache_website_domain}})'
  supported_distributions:
    - 'Debian'
  user: omit
  paths: []
  packages: []
  notifications: []
  port_configs: []
  services: []
  dashboards: []
  dashboard_host_rows: "{{inventory_hostname_short | dashboard_rows_website('apache', apache_website_domain)}}"
  monitoring_checks:
    - {type: 'website', domain: '{{apache_website_domain}}', kind: 'apache'}
