apache_website_domain: None
apache_website_locations: []
apache_website_htpasswds: []
apache_website_is_https: True
apache_website_log_anonymously: True
apache_website_net_accesses:
  - loopback
apache_website_add_www_redirects: '{{(apache_website_domain | split(".") | length) < 3}}'