allow_duplicates: yes

dependencies:
  - role: apache-website
    apache_website_domain: '{{static_website_domain}}'
    apache_website_locations: '{{static_website_locations + static_website_default_locations}}'
    apache_website_htpasswds: '{{static_website_htpasswds}}'
    apache_website_net_accesses: '{{static_website_net_accesses}}'
    apache_website_redirects: '{{static_website_redirects}}'
    apache_website_rewrites: '{{static_website_rewrites}}'
    when: static_website_server_flavor == 'apache'

  - role: fail
    msg: 'Unknown static_website_server_flavor "{{static_website_server_flavor | default("<empty>")}}"'
    when: static_website_server_flavor not in ['apache']
