- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{ansible_distribution}}' in '{{role_path|basename}}' role"
  when: 'ansible_distribution not in ["Debian"]'

- name: Ensure common directories exists
  file:
    path: '{{item}}'
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - '{{common_directories_db}}'
    - '{{common_directories_data_base}}'
    - '{{common_directories_data_dir1}}'
