- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{apache_webserver_common_role_tasks_config}}'

- name: Make custom confs available
  template:
    dest: '/etc/apache2/conf-available/{{item}}'
    src: '{{item}}.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - log_formats.conf
    - server_headers.conf
    - error_documents.conf
  notify:
    reload apache

- name: Enable needed confs
  file:
    state: link
    dest: '/etc/apache2/conf-enabled/{{item}}'
    src: '/etc/apache2/conf-available/{{item}}'
    owner: root
    group: root
    mode: 0444
  with_items:
    - log_formats.conf
    - server_headers.conf
    - error_documents.conf
  notify:
    reload apache

- name: Configure modsecurity
  template:
    dest: '/etc/modsecurity/modsecurity.conf'
    src: 'modsecurity.conf.j2'
    owner: root
    group: root
    mode: 0444
  notify:
    reload apache

- name: Configure OWASP modsecurity rule set
  template:
    dest: '/etc/modsecurity/crs/crs-setup.conf'
    src: 'crs-setup.conf.j2'
    owner: root
    group: root
    mode: 0444
  notify:
    reload apache

- name: Make custom mods available
  template:
    dest: '/etc/apache2/mods-available/{{item}}'
    src: '{{item}}.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - status_basic.conf
    - security_rules_global.conf
  notify:
    reload apache

- name: Enable needed mods
  file:
    state: link
    dest: '/etc/apache2/mods-enabled/{{item}}'
    src: '/etc/apache2/mods-available/{{item}}'
    owner: root
    group: root
    mode: 0444
  with_items:
    - authnz_ldap.load
    - cgi.load
    - headers.load
    - proxy.conf
    - proxy.load
    - proxy_http.load
    - ldap.load
    - ldap.conf
    - rewrite.load
    - security_rules_global.conf
    - security2.conf
    - security2.load
    - ssl.conf
    - ssl.load
    - status_basic.conf
    - status.load
    - socache_shmcb.load
  notify:
    reload apache

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{apache_webserver_common_role_tasks_config}}'

- name: Drop undesired default configurations
  file:
    state: absent
    dest: '/etc/apache2/conf-enabled/{{item}}'
  with_items:
    - icinga.conf # Icinga from apt configures its site via a conf. That
                  # gets in the way of our site conf. Hence, we drop it
    - icinga-web.conf # (See icinga.conf)
    - serve-cgi-bin.conf # We do not want default cgi-bin serving
    - javascript-common.conf # No automatic javascript exporting
  notify:
    reload apache

- name: Drop undesired modules
  file:
    state: absent
    dest: '/etc/apache2/mods-enabled/{{item}}'
  with_items:
    - status.conf # Some distros do not restrict status module to local
                  # requests, hence we roll our own config. That way we
                  # should be say even after updates.
  notify:
    reload apache

- name: Drop default site
  file:
    state: absent
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify:
    reload apache

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{apache_webserver_common_role_tasks_config}}'
