pop3_server_port: 110
pop3_server_ssl_port: 995
pop3_server_log_level: '{{logging_default_log_level}}'
pop3_server_net_accesses:
  - loopback
pop3_server_db_directory: '{{common_directories_db}}/dovecot'
pop3_server_index_directory: '{{pop3_server_db_directory}}/index'
pop3_server_control_directory: '{{pop3_server_db_directory}}/control'
pop3_server_users: {}

pop3_server_log_dir: '/var/log/dovecot'
pop3_server_effective_data_disk: '{{common_directories_default_data_dir}}'
pop3_server_effective_data_dir: '{{pop3_server_effective_data_disk}}/pop3-server'
pop3_server_effective_log_dir: '{{pop3_server_effective_data_dir}}/logs'

pop3_server_common_role_tasks_config:
  role: pop3_server
  supported_distributions:
    - 'Debian'
  user: dovecot
  paths:
    - {path: '{{pop3_server_db_directory}}', user: mail, group: mail, mode: '770'}
    - {path: '{{pop3_server_index_directory}}', user: mail, group: mail, mode: '770'}
    - {path: '{{pop3_server_control_directory}}', user: mail, group: mail, mode: '770'}
    - '{{pop3_server_effective_data_dir}}'
    - {path: '{{pop3_server_effective_log_dir}}', group: adm, mode: '2750'}
    - {state: link, path: '{{pop3_server_log_dir}}', source: '{{pop3_server_effective_log_dir}}', group: adm}
    - {state: touch, path: '{{pop3_server_effective_log_dir}}/dovecot.log', group: adm, mode: '640' }
  packages:
    - dovecot-pop3d
  notifications:
    - dovecot restart
  port_configs:
    - name: POP3
      port: '{{pop3_server_port}}'
      incoming_net_accesses: '{{pop3_server_net_accesses}}'
      skip: '{{pop3_server_port == 0}}'
    - name: POP3S
      port: '{{pop3_server_ssl_port}}'
      incoming_net_accesses: '{{pop3_server_net_accesses}}'
      skip: '{{pop3_server_ssl_port == 0}}'
  services:
    - dovecot
  log_files:
    - file: '{{pop3_server_log_dir}}/dovecot.log'
      group: dovecot
      item: main
      description: 'Dovecot Log'
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks:
    - {name: Daemon, command: dovecot, user: root}
