allow_duplicates: yes

dependencies:
  - role: website-common
    website_common_domain: '{{apache_website_domain}}'
    website_common_htpasswds: '{{apache_website_htpasswds}}'
    website_common_is_https: '{{apache_website_is_https}}'
    website_common_add_www_redirects: '{{apache_website_add_www_redirects}}'
    website_common_kind: apache
