# qa:lint:distribution-independent
# qa:lint:no-log-level-needed

- name: 'Add phone dashboard'
  set_fact:
    dashboards: "{{dashboards + ['Phones' | dashboard_phones]}}"
  changed_when: False
  tags:
    - always
