# lint:no-logging-needed

# We would want to have the common-role-tasks, like common-role-task-start etc,
# here. However, when having them in tasks/main.yml, Ansible fails to resolve
# variables properly. For example when running for static websites
# (static-website-foo -> static-website -> apache-website -> website-common),
# `static_website_domain` (which gits indirectly used within
# `website_common_common_role_tasks_config`) has a proper value in this
# file. But in the imported `common-role-tasks-*` role, it is empty which makes
# it's indirect uses break the config. Simply passing `static_website_domain`
# explicitly to the imported role does not work, as Ansible complains about
# detected loops. But for static-websites, one can work around it by first
# `set_fact`-ing the value to some temporary variable, and then passing that set
# variable to the imported role. While that works for `website-common` when used
# through `static-website`, it does not work for other sites. For example it
# breaks for the use from the `graphite` role. Coming from the `graphite` role,
# Ansible (even with the above set_fact and with adding a default) complains
# that `static_website_domain` is undefined. We tried many more things, but
# could not get it to work reliably in all use-cases. So we resort to calling
# the `common-role-tasks-*` roles from `meta`, which seems to work
# reliably. This is not ideal, as it does not allow to easily run tasks between
# `common-role-tasks-*` roles. But at least it's working reliably.

- name: Load credentials
  include_vars: credentials.yml

- name: Create htpasswords
  template:
    dest: '{{web_site_root_dir}}/{{website_common_domain}}/htpasswds/{{item.key}}'
    src: 'htpasswd.j2'
    owner: www-data
    group: ssl-cert
    mode: 0440
  with_items: '{{website_common_htpasswds | dict2items}}'
  notify:
    reload webserver
