- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian", "Gentoo"]'

- name: Create directories
  file:
    state: directory
    dest: "{{item['path']}}"
    owner: "{{item['user'] | default('root')}}"
    group: "{{item['user'] | default('root')}}"
    mode: "{{'775' if (item['writable'] | default(False)) else '555'}}"
  with_items:
    - { path: '{{common_directories_data_dir1}}/website-{{website_common_domain}}' }
    - { path: '{{common_directories_data_dir1}}/website-{{website_common_domain}}/htdocs', user: www-data }
    - { path: '{{common_directories_data_dir1}}/website-{{website_common_domain}}/htpasswds' }
    - { path: '{{common_directories_data_dir1}}/website-{{website_common_domain}}/logs', user: www-data, writable: True }
  notify:
    reload webserver

- name: Link effective site directory into place
  file:
    state: link
    dest: '{{web_site_root_dir}}/{{website_common_domain}}'
    src: '{{common_directories_data_dir1}}/website-{{website_common_domain}}'
  notify:
    reload webserver

- name: Load credentials
  include_vars: credentials.yml

- name: Create htpasswords
  template:
    dest: '{{web_site_root_dir}}/{{website_common_domain}}/htpasswds/{{item.name}}'
    src: 'htpasswd.j2'
    owner: www-data
    group: ssl-cert
    mode: 0440
  with_items: '{{website_common_htpasswds}}'
  notify:
    reload webserver
