- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{website_common_common_role_tasks_config}}'

- name: Load credentials
  include_vars: credentials.yml

- name: Create htpasswords
  template:
    dest: '{{web_site_root_dir}}/{{website_common_domain}}/htpasswds/{{item.key}}'
    src: 'htpasswd.j2'
    owner: www-data
    group: ssl-cert
    mode: 0440
  with_items: '{{website_common_htpasswds | dict2items}}'
  notify:
    reload webserver

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{website_common_common_role_tasks_config}}'

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{website_common_common_role_tasks_config}}'
