ldap_server_organization: '{{company_name}}'

ldap_server_log_level: '{{logging_default_log_level}}'

ldap_server_mdb_access:
  - 'attrs=userPassword,shadowLastChange by self write by anonymous auth by dn="cn=admin,{{ldap_server_base_dn}}" write by * none'
  - 'dn.base="" by * read'
  - '* by dn="cn=admin,{{ldap_server_base_dn}}" write by * read'

ldap_server_uid_start: 10000
ldap_server_password_scheme: SSHA # Unfortunately, OpenLDAP does not
# support strong algos. SSHA is the strongest one there is. So we pick
# that one.

ldap_server_ldapscripts_log_file: '/var/log/ldapscripts.log'

ldap_server_net_accesses:
  - loopback

ldap_server_extra_schemas:
  - cn: openssh-lpk
    attributes:
      olcAttributeTypes: "{0}( 1.3.6.1.4.1.24552.500.1.1.1.13 NAME 'sshPublicKey' DESC 'MANDATORY: OpenSSH Public key' EQUALITY octetStringMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.40 )"
      olcObjectClasses: "{0}( 1.3.6.1.4.1.24552.500.1.1.2.0 NAME 'ldapPublicKey' SUP top AUXILIARY DESC 'MANDATORY: OpenSSH LPK objectclass' MUST ( uid ) MAY ( sshPublicKey ) )"
  - cn: auxiliary-posix-group
    attributes:
      olcObjectClasses: "{0}( 2.25.339083012180962215434722360736538961521 NAME 'auxiliaryPosixGroup' SUP top AUXILIARY DESC 'Auxiliary posixGroup' MUST ( cn $ gidNumber ) MAY ( userPassword $ memberUid $ description ) )"

ldap_server_common_role_tasks_config:
  role: ldap-server
  supported_distributions:
    - 'Debian'
  user: openldap
  extra_groups:
    - ssl-cert
  paths: []
  packages:
    - slapd
    - ldap-utils
    - ldapscripts
    - python-ldap # Needed only for Ansible's LDAP modules
  notifications:
    - reload slapd
  port_configs:
    - name: LDAP
      port: '{{ldap_server_port}}'
      incoming_net_accesses: '{{ldap_server_net_accesses}}'
  services:
    - slapd
  log_files: []
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks:
    - {'name': 'Daemon', command: 'slapd'}
