- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{diamond_common_role_tasks_config}}'

- name: Configure diamond
  template:
    dest: /etc/diamond/diamond.conf
    src: diamond.conf.j2
    owner: root
    group: root
    mode: 0444
  notify:
    reload diamond

- name: Install custom collectors
  template:
    dest: '{{diamond_collector_dir}}/{{item}}Collector.py'
    src: '{{item}}Collector.py.j2'
    owner: root
    group: root
    mode: 0444
  with_items: '{{diamond_custom_collectors}}'
  notify:
    reload diamond

- name: Configure collectors
  template:
    dest: '{{diamond_collector_conf_dir}}/{{item}}Collector{{diamond_collector_conf_extension}}'
    src: '{{item}}Collector{{diamond_collector_conf_extension}}.j2'
    owner: root
    group: root
    mode: 0444
  with_items: '{{diamond_custom_collectors + diamond_custom_collector_configs}}'
  notify:
    reload diamond

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{diamond_common_role_tasks_config}}'

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{diamond_common_role_tasks_config}}'
