- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian"]'

- name: Create paths without ownership
  file:
    state: "{{item['state'] | default('directory')}}"
    path: "{{item['path'] | default(item)}}"
    src: "{{item['source'] | default('')}}"
    mode: 0755
  with_items: "{{diamond_path_config['paths']}}"
  notify:
    reload diamond

- name: Grant diamond user access to log files
  user:
    state: present
    name: diamond
    append: yes
    createhome: no
    groups: adm
  when: '"apache" in group_names or "nginx" in group_names'

- name: Configure diamond
  template:
    dest: /etc/diamond/diamond.conf
    src: diamond.conf.j2
    owner: root
    group: root
    mode: 0444
  notify:
    reload diamond

- name: Configure collectors
  template:
    dest: '{{diamond_collector_conf_dir}}/{{item}}Collector{{diamond_collector_conf_extension}}'
    src: '{{item}}Collector{{diamond_collector_conf_extension}}.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
    - DiskUsage
  notify:
    reload diamond

- name: Install diamond packages
  apt:
    name:
      - diamond
    state: present

- name: Set file ownership
  file:
    state: "{{item['state'] | default('directory')}}"
    path: "{{item['path'] | default(item)}}"
    owner: "{{diamond_path_config['owner']}}"
    group: "{{diamond_path_config['group'] | default(diamond_path_config['owner'])}}"
    src: "{{item['source'] | default('')}}"
    mode: 0755
  with_items: "{{diamond_path_config['paths']}}"
  notify:
    reload diamond
