- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian"]'

- name: Install OpenLDAP client tools
  apt:
    name:
      - ldap-utils
      - nslcd
    state: present
  when: 'qhost_distribution == "Debian"'

- name: Configure openldap client
  template:
    dest: '/etc/ldap/ldap.conf'
    src: ldap.conf.j2
    owner: root
    group: root
    mode: 0444

- name: Configure nslcd
  template:
    dest: '/etc/nslcd.conf'
    src: nslcd.conf.j2
    owner: root
    group: root
    mode: 0444
  notify:
    - restart nslcd
    - restart nscd

- name: Setup home directory creation
  template:
    dest: '/usr/share/pam-configs/mkhomedir'
    src: mkhomedir.pam.j2
    owner: root
    group: root
    mode: 0444
  notify:
    regenerate pam

- name: Setup helper script to get ssh keys
  template:
    dest: '/usr/bin/get-ldap-ssh-public-key'
    src: get-ldap-ssh-public-key.sh.j2
    owner: root
    group: root
    mode: 0555
    force: no
