# qa:lint:no-log-level-needed

- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{ldap_client_early_common_role_tasks_config}}'

- name: Configure openldap client
  template:
    dest: '/etc/ldap/ldap.conf'
    src: ldap.conf.j2
    owner: root
    group: root
    mode: 0444

- name: Configure nslcd
  template:
    dest: '/etc/nslcd.conf'
    src: nslcd.conf.j2
    owner: root
    group: root
    mode: 0444
  notify:
    - restart nslcd
    - restart nscd

- name: Setup home directory creation
  template:
    dest: '/usr/share/pam-configs/mkhomedir'
    src: mkhomedir.pam.j2
    owner: root
    group: root
    mode: 0444
  notify:
    regenerate pam

- name: Setup helper script to get ssh keys
  template:
    dest: '/usr/bin/get-ldap-ssh-public-key'
    src: get-ldap-ssh-public-key.sh.j2
    owner: root
    group: root
    mode: 0555
    force: no

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{ldap_client_early_common_role_tasks_config}}'

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{ldap_client_early_common_role_tasks_config}}'
