unmanaged_host_monitor_ssh: False

unmanaged_host_common_role_tasks_config:
  role: unmanaged-host
  supported_distributions: any
  user: omit
  paths: []
  packages: []
  notifications: []
  port_configs: []
  services: []
  log_files: []
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks:
    - {name: Accepting, type: port, port: '{{ssh_server_port}}', service: ssh, skip: '{{not unmanaged_host_monitor_ssh}}'}
