unmanaged_host_common_role_tasks_config:
  role: unmanaged-host
  supported_distributions: any
  user: omit
  paths: []
  packages: []
  notifications: []
  port_configs: []
  services: []
  log_files: []
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks: []
