- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{ansible_distribution}}' in 'name-service-switch' role"
  when: 'ansible_distribution not in ["Debian"]'

- name: Configure name service switch
  copy:
    dest: '/etc/nsswitch.conf'
    src: 'nsswitch.conf'
    owner: root
    group: root
    mode: 0444
  notify:
    - restart nscd
