- name: common-early (generic)
  hosts: '!unmanaged'
  roles:
    - role: emergency-user
      tags:
        - 'emergency-user'

    - role: hostname
      tags:
        - 'hostname'

    - role: common-packages
      tags:
        - 'common-packages'

    - role: network-tuner
      tags:
        - 'network-tuner'
