- name: common-early (generic)
  hosts: '!unmanaged'
  roles:
    - role: emergency-user
      tags:
        - 'emergency-user'

    - role: hostnames
      tags:
        - 'hostnames'

    - role: firewall-early
      tags:
        - 'firewall'
        - 'firewall-early'

    - role: common-packages
      tags:
        - 'common-packages'

    - role: common-directories
      tags:
        - 'common-directories'

    - role: network-tuner
      tags:
        - 'network-tuner'

    - role: ssh-server
      tags:
        - 'ssh-server'

    - role: locale
      tags:
        - locale

    - role: time
      tags:
        - time

    - role: ldap-client-early
      tags:
        - ldap-client-early
        - ldap-client
        - ldap

    - role: name-service-switch
      tags:
        - name-service-switch
