- name: common-late (generic)
  hosts: '!unmanaged'
  roles:
    - role: apache-website-default
      when: (apache_websites | default([]) | length) > 1
      tags:
        - apache-website-default
        - website

    - role: icinga-client
      tags:
       - icinga-client
       - icinga

    - role: firewall-late
      tags:
        - 'firewall'
        - 'firewall-late'

    - role: ldap-client-late
      tags:
       - ldap-client-late
       - ldap-client
       - ldap
