- name: common-late (start)
  hosts: '!unmanaged'
  roles:
    - role: apache-website-default
      when: (apache_websites | default([]) | length) > 1
      tags:
        - apache-website-default
        - website

    - role: diamond
      tags:
        - diamond

- name: common-late (generic for all, even unmanaged)
  hosts: all
  gather_facts: no
  roles:
    - role: icinga-client
      tags:
       - icinga-client
       - icinga

- name: common-late (finish)
  hosts: '!unmanaged'
  roles:
    - role: firewall-late
      tags:
        - 'firewall'
        - 'firewall-late'

    - role: ldap-client-late
      tags:
       - ldap-client-late
       - ldap-client
       - ldap
