- name: common-early (generic)
  hosts: '!unmanaged'
  roles:
    - role: emergency-user
      tags:
        - 'emergency-user'

    - role: hostname
      tags:
        - 'hostname'

    - role: firewall-early
      tags:
        - 'firewall'
        - 'firewall-early'

    - role: common-packages
      tags:
        - 'common-packages'

    - role: common-directories
      tags:
        - 'common-directories'

    - role: network-tuner
      tags:
        - 'network-tuner'

    - role: ssh-server
      tags:
        - 'ssh-server'

    - role: time
      tags:
        - time
