- name: "ZTE Modem metrics"
  hosts: zte_modem_metric_fetchers
  roles:
    - role: zte-modem-metric-fetcher
      tags:
        - zte-modem-metric-fetcher

- name: "biblioweb libraries"
  hosts: libraries_biblioweb_ats
  roles:
    - role: libraries-biblioweb-at
      tags:
        - libraries-biblioweb-at
        - libraries

- name: "Phones from Hot Austria"
  hosts: phones_hot_ats
  roles:
    - role: phones-hot-at
      tags:
        - phones-hot-at
        - phones

- name: "Phones"
  hosts: grafanas
  roles:
    - role: phones
      tags:
        - phones
