- name: "HP Printer"
  hosts: hp_printers
  gather_facts: no
  roles:
    - role: hp-printer
      tags:
        - hp-printer

- name: "Unmanaged Hosts"
  hosts: unmanaged
  gather_facts: no
  roles:
    - role: unmanaged-host
      tags:
        - unmanaged-host
        - unmanaged
