allow_duplicates: no

dependencies:
  - role: apache-website
    apache_website_domain: 'default'
    apache_website_is_https: False
    apache_website_add_www_redirects: False
    apache_website_log_anonymously: False # Requests to this site are
      # either someone trying to break in or from us. So either way we
      # can/should log request details.
    apache_website_net_accesses: []
    apache_website_log_level: '{{apache_website_default_log_level}}'
    apache_website_locations:
      - name: /server-status
        auth_merging: Off
        expose_server_status: True
        net_accesses: ['loopback']
