- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{pop3_server_common_role_tasks_config}}'

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{pop3_server_common_role_tasks_config}}'

- name: Load secrets
  include_vars: secrets.yml

- name: Configure allowed users
  template:
    dest: '/etc/dovecot/passwd'
    src: passwd.j2
    owner: dovecot
    group: dovecot
    mode: 0440
  notify:
    dovecot restart

- name: Configure dovecot
  template:
    dest: '/etc/dovecot/dovecot.conf'
    src: dovecot.conf.j2
    owner: root
    group: root
    mode: 0444
  notify:
    dovecot restart

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{pop3_server_common_role_tasks_config}}'
