- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{ansible_distribution}}' in '{{role_path|basename}}' role"
  when: 'ansible_distribution not in ["Debian"]'

- name: Install needed packages
  apt:
    name: dovecot-pop3d
    state: present

- name: Ensure index directory exists
  file:
    path: '{{item}}'
    state: directory
    owner: mail
    group: mail
    mode: 0770
  with_items:
    - '{{pop3_server_db_directory}}'
    - '{{pop3_server_index_directory}}'
    - '{{pop3_server_control_directory}}'

- name: Load secrets
  include_vars: secrets.yml

- name: Configure allowed users
  template:
    dest: '/etc/dovecot/passwd'
    src: passwd.j2
    owner: dovecot
    group: dovecot
    mode: 0440
  notify:
    dovecot restart

- name: Configure dovecot
  template:
    dest: '/etc/dovecot/dovecot.conf'
    src: dovecot.conf.j2
    owner: root
    group: root
    mode: 0444
  notify:
    dovecot restart

- name: Updating port config
  set_fact:
    firewall_late_port_config: '{{firewall_late_port_config | default({}) | update_dict({
      pop3_server_port: {
        "name": "POP3",
        "protocol": "tcp",
        "incoming_net_accesses": pop3_server_net_accesses,
      }
    }, merge_lists=True)}}'
  changed_when: False
  when: 'pop3_server_port != 0'
  tags:
    - always

- name: Updating port config
  set_fact:
    firewall_late_port_config: '{{firewall_late_port_config | default({}) | update_dict({
      pop3_server_ssl_port: {
        "name": "POP3S",
        "protocol": "tcp",
        "incoming_net_accesses": pop3_server_net_accesses,
      }
    }, merge_lists=True)}}'
  changed_when: False
  when: 'pop3_server_ssl_port != 0'
  tags:
    - always
