- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{vpn_common_role_tasks_config}}'
  when: 'inventory_hostname | host_nets(net_configs, type="vpn")| list'

- name: Bring static keys in place
  #
  # Generate keys via
  #
  #    openvpn --genkey --secret vpn-name.key
  #
  copy:
    dest: '/etc/openvpn/{{item | net_slug(inventory_hostname)}}.key'
    src: '{{item | net_slug(None)}}.key'
    owner: root
    group: root
    mode: 0400
  with_items: '{{inventory_hostname | host_nets(net_configs, type="vpn")| list}}'
  notify:
    - reload openvpn-{{qhost_distribution}}

- name: Render configs
  template:
    dest: '/etc/openvpn/{{item | net_slug(inventory_hostname)}}.conf'
    src: 'openvpn.conf.j2'
    owner: root
    group: root
    mode: 0400
  with_items: '{{inventory_hostname | host_nets(net_configs, type="vpn")| list}}'
  notify:
    - reload openvpn-{{qhost_distribution}}

- name: Bring service config into place
  file:
    state: link
    dest: '/etc/init.d/openvpn.{{item | net_slug(inventory_hostname)}}'
    src: '/etc/init.d/openvpn'
    owner: 'root'
    group: 'root'
    mode: 0755
    force: True
  with_items: '{{inventory_hostname | host_nets(net_configs, type="vpn")| list}}'
  when: 'qhost_distribution == "Gentoo"'
  notify:
    - reload openvpn-{{qhost_distribution}}

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{vpn_common_role_tasks_config}}'
  when: 'inventory_hostname | host_nets(net_configs, type="vpn")| list'

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{vpn_common_role_tasks_config}}'
  when: 'inventory_hostname | host_nets(net_configs, type="vpn")| list'
