- name: reload openvpn-Debian
  systemd:
    name: openvpn
    state: reloaded
    daemon_reload: yes

- name: reload openvpn-Gentoo
  service:
    name: 'openvpn.{{item | net_slug(inventory_hostname)}}'
    state: restarted
  with_items: '{{inventory_hostname | host_nets(net_configs, type="vpn") | list}}'
