# qa:lint:no-log-level-needed

- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{icinga_client_late_common_role_tasks_config}}'
  when: '"unmanaged" not in group_names'

- name: Setup nrpe checks config
  template:
    dest: /etc/nagios/nrpe_ansiblized_checks.cfg
    src: ansiblized_checks.cfg.j2
    owner: root
    group: root
    mode: 0444
  notify:
    - reload nagios-nrpe-server
  when: '"unmanaged" not in group_names'

- name: Setup remote service configs
  template:
    dest: '{{icinga_server_object_path}}/services/{{inventory_hostname}}.cfg'
    src: services.cfg.j2
    owner: root
    group: root
    mode: 0444
  delegate_to: "{{item}}"
  with_items: '{{groups["icinga_servers"]}}'
  notify:
    - reload icinga

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{icinga_client_late_common_role_tasks_config}}'
  when: '"unmanaged" not in group_names'

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{icinga_client_late_common_role_tasks_config}}'
  when: '"unmanaged" not in group_names'

