- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{smtp_server_common_role_tasks_config}}'

- name: Render aliases
  template:
    dest: '/etc/mail/aliases{{"-" if item["key"] else ""}}{{item["key"]}}'
    src: aliases.j2
    owner: root
    group: root
    mode: 0444
  with_items: '{{smtp_server_alias_files | dict2items}}'

- name: Setup DKIM private keys
  copy:
    dest: '/etc/exim4/dkim/dkim.{{item}}.private.key'
    src: 'dkim.{{item}}.private.key'
    owner: Debian-exim
    group: root
    mode: 0400
  with_items: '{{smtp_server_dkim_domains}}'

- name: Setup main exim config
  template:
    dest: '/etc/exim4/exim4.conf'
    src: exim4.conf.j2
    owner: root
    group: root
    mode: 0444
  notify:
    reload exim

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{smtp_server_common_role_tasks_config}}'

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{smtp_server_common_role_tasks_config}}'
