- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian"]'

- name: Configure {{apache_website_domain}} site
  template:
    dest: '{{web_site_root_dir}}/{{apache_website_domain}}/conf/{{apache_website_domain}}.conf'
    src: 'site.conf.j2'
    owner: root
    group: root
    mode: 0444
  notify:
    reload apache

- name: Collect hosted website
  set_fact:
    apache_updated_websites: '{{apache_updated_websites | default([])}} + [ "{{apache_website_domain}}" ]'
  when: 'apache_website_domain not in (apache_updated_websites | default([]))'
  changed_when: False

- name: Collect hosted website
  set_fact:
    apache_websites: '{{apache_websites | default([])}} + [ "{{apache_website_domain}}" ]'
  when: 'apache_website_domain not in (apache_websites | default([]))'
  changed_when: False
  tags:
    - always

- name: 'Add dashboard rows'
  set_fact:
    dashboard_host: "{{dashboard_host | dashboard_add_rows_website(inventory_hostname_short, 'apache', apache_website_domain)}}"
  changed_when: False
  tags:
    - always
