ldap_client_early_common_role_tasks_config:
  role: ldap-client
  supported_distributions:
    - 'Debian'
  user: omit
  paths: []
  packages:
    - ldap-utils
    - nscd
    - nslcd
  notifications: []
  port_configs: []
  services: []
  log_files: []
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks: []
