icinga_client_ip_address: "{{(net_configs[icinga_client_server_net]|net_ip('local', inventory_hostname)) if icinga_client_server_net is defined else ''}}"
icinga_client_server_ip_address: "{{(net_configs[icinga_client_server_net]|net_ip('local', groups['icinga_servers'][0])) if icinga_client_server_net is defined else icinga_server_web_host}}"
icinga_client_monitor_ssh: True
icinga_client_nrpe_server_port: 5666
icinga_client_net_accesses: '{{([{"net_key": icinga_client_server_net, "hosts": [icinga_client_server_ip_address]}]) if icinga_client_server_net is defined else []}}'
icinga_client_ping_net_accesses: '{{icinga_client_net_accesses}}'
icinga_client_nrpe_net_accesses: '{{icinga_client_net_accesses}}'
icinga_client_log_level: '{{logging_default_log_level}}'
