icinga_client_ip_address: "{{(net_configs[icinga_client_server_net]|net_ip('local', inventory_hostname)) if icinga_client_server_net is defined else ''}}"
icinga_client_server_ip_address: "{{(net_configs[icinga_client_server_net]|net_ip('local', groups['icinga_servers'][0])) if icinga_client_server_net is defined else icinga_server_web_host}}"
icinga_client_nrpe_server_port: 5666
icinga_client_net_accesses: '{{([{"net_key": icinga_client_server_net, "hosts": [icinga_client_server_ip_address]}]) if icinga_client_server_net is defined else []}}'
icinga_client_ping_net_accesses: '{{icinga_client_net_accesses}}'
icinga_client_nrpe_net_accesses: '{{icinga_client_net_accesses}}'
icinga_client_log_level: '{{logging_default_log_level}}'

icinga_client_common_role_tasks_config:
  role: icinga-client
  supported_distributions:
    - 'Debian'
  user: nagios
  paths:
    - /etc/nagios
  packages:
    - nagios-plugins
    - nagios-nrpe-server
    - perl # check_file_age complains about missing Tie::Hash::NamedCapture.pm otherwise
  notifications:
    - reload nagios-nrpe-server
  port_configs:
    - name: NRPE
      port: '{{icinga_client_nrpe_server_port}}'
      incoming_net_accesses: '{{icinga_client_nrpe_net_accesses}}'
    - name: ICMP
      protocol: icmp
      icmp_type: echo-request
      incoming_net_accesses: '{{icinga_client_ping_net_accesses}}'
  services:
    - nagios-nrpe-server
  log_files: []
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks: []
