- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{role_path|basename}}' role"
  when: 'qhost_distribution not in ["Debian"]'

- name: Create paths without ownership
  file:
    state: "{{item['state'] | default('directory')}}"
    path: "{{item['path'] | default(item)}}"
    src: "{{item['source'] | default('')}}"
    mode: 0755
  with_items: "{{graphite_path_config['paths']}}"
  notify:
    reload carbon

- name: Configure carbon storage schemas
  template:
    dest: '/etc/carbon/{{item}}.conf'
    src: '{{item}}.conf.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
  - carbon
  - storage-schemas
  - storage-aggregation
  notify:
    - reload carbon
    - sync carbon-database

- name: Configure carbon defaults
  template:
    dest: '/etc/default/graphite-carbon'
    src: graphite-carbon.j2
    owner: root
    group: root
    mode: 0444
  notify:
    reload carbon

- name: Set up attic management script
  template:
    dest: '/usr/bin/graphite-manage-attic'
    src: graphite-manage-attic.j2
    owner: root
    group: root
    mode: 0555

- name: Install graphite packages
  apt:
    name:
      - graphite-web
      - graphite-carbon
      - libapache2-mod-wsgi-py3
    state: present

- name: Set file ownership
  file:
    state: "{{item['state'] | default('directory')}}"
    path: "{{item['path'] | default(item)}}"
    owner: "{{graphite_path_config['owner']}}"
    group: "{{graphite_path_config['group'] | default(graphite_path_config['owner'])}}"
    src: "{{item['source'] | default('')}}"
    mode: 0755
  with_items: "{{graphite_path_config['paths']}}"
  notify:
    reload carbon

- name: Load salt
  include_vars: salt.yml

- name: Configure graphite local settings
  template:
    dest: '/etc/graphite/local_settings.py'
    src: local_settings.py.j2
    owner: _graphite
    group: _graphite
    mode: 0440
  notify:
    - sync carbon-database

- name: Set up cron job move stale entities to attic
  cron:
    state: present
    user: _graphite
    name: "graphite-move-stale-entities-to-attic"
    hour: "{{inventory_hostname | hashing_mod(24, 11)}}"
    minute: "{{inventory_hostname | hashing_mod(60, 11)}}"
    job: "/usr/bin/graphite-manage-attic --move-stale-entities --verbose >>{{graphite_log_dir}}/graphite-manage-attic.log 2>&1"

- name: Updating port config
  set_fact:
    firewall_late_port_config: '{{firewall_late_port_config | default({}) | update_dict({
      graphite_line_receiver_port: {
        "name": "GRAPHITE_LINE_RECEIVER",
        "protocol": "tcp",
        "incoming_net_accesses": graphite_receive_net_accesses,
      },
      graphite_cache_query_port: {
        "name": "GRAPHITE_CACHE",
        "protocol": "tcp",
        "incoming_net_accesses": graphite_query_net_accesses,
      }
    }, merge_lists=True)}}'
  changed_when: False
  tags:
    - always
