- name: Common role tasks at start
  import_role:
    name: common-role-tasks-start
  vars:
    common_role_tasks_start_config: '{{graphite_common_role_tasks_config}}'

- name: Configure carbon storage schemas
  template:
    dest: '/etc/carbon/{{item}}.conf'
    src: '{{item}}.conf.j2'
    owner: root
    group: root
    mode: 0444
  with_items:
  - carbon
  - storage-schemas
  - storage-aggregation
  notify:
    - reload carbon
    - sync carbon-database

- name: Configure carbon defaults
  template:
    dest: '/etc/default/graphite-carbon'
    src: graphite-carbon.j2
    owner: root
    group: root
    mode: 0444
  notify:
    reload carbon

- name: Set up attic management script
  template:
    dest: '/usr/bin/graphite-manage-attic'
    src: graphite-manage-attic.j2
    owner: root
    group: root
    mode: 0555

- name: Load salt
  include_vars: salt.yml

- name: Configure graphite local settings
  template:
    dest: '/etc/graphite/local_settings.py'
    src: local_settings.py.j2
    owner: _graphite
    group: _graphite
    mode: 0440
  notify:
    - sync carbon-database

- name: Common role tasks for installing packages
  import_role:
    name: common-role-tasks-package-install
  vars:
    common_role_tasks_package_install_config: '{{graphite_common_role_tasks_config}}'

- name: Set up cron job move stale entities to attic
  cron:
    state: present
    user: _graphite
    name: "graphite-move-stale-entities-to-attic"
    hour: "{{inventory_hostname | hashing_mod(24, 11)}}"
    minute: "{{inventory_hostname | hashing_mod(60, 11)}}"
    job: "/usr/bin/graphite-manage-attic --move-stale-entities --verbose >>{{graphite_log_dir}}/graphite-manage-attic.log 2>&1"

- name: 'Add graphite dashboard row'
  set_fact:
    dashboard_host: '{{dashboard_host | dashboard_add_row(inventory_hostname_short | dashboard_row_graphite)}}'
  changed_when: False
  tags:
    - always

- name: Common role tasks at end
  import_role:
    name: common-role-tasks-end
  vars:
    common_role_tasks_end_config: '{{graphite_common_role_tasks_config}}'
