diamond_log_dir: '/var/log/diamond'

diamond_effective_data_disk: '{{common_directories_default_data_dir}}'
diamond_effective_data_dir: '{{diamond_effective_data_disk}}/diamond'
diamond_effective_log_dir: '{{diamond_effective_data_dir}}/logs'

diamond_common_role_tasks_config:
  role: diamond
  supported_distributions:
    - 'Debian'
  user: diamond
  extra_groups:
    - "{{'adm' if 'apache' in group_names or 'nginx' in group_names else ''}}"
  paths:
    - '{{diamond_effective_data_dir}}'
    - '{{diamond_effective_log_dir}}'
    - {state: link, path: '{{diamond_log_dir}}', source: '{{diamond_effective_log_dir}}'}
    - '{{diamond_collector_conf_dir}}'
    - /etc/diamond
  packages:
    - diamond
    - python-requests
  notifications:
    - reload diamond
  port_configs: []
  services:
    - diamond
  log_files:
    - file: '{{diamond_log_dir}}/diamond.log'
      group: diamond
      item: main
      description: Diamond logs
      skip: "{{diamond_log_level == 'none'}}"
  dashboards: []
  dashboard_host_rows: []
  monitoring_checks:
    - {command: 'python', argument: '/usr/bin/diamond'}

diamond_metric_proxy_hosts_ssh: []
diamond_metric_proxy_hosts_jetdirect: []
diamond_custom_collectors:
    - JetDirect
    - ModdedHttpd
    - ProxyBulkFile
    - ProxyCPU
    - ProxyLoadAverage
    - ProxyMemory
    - ProxyNetwork
diamond_custom_collector_configs:
    - DiskUsage

diamond_log_level: '{{logging_default_log_level}}'
