diamond_log_dir: '/var/log/diamond'

diamond_effective_data_disk: '{{common_directories_data_dir1}}'
diamond_effective_data_dir: '{{diamond_effective_data_disk}}/diamond'
diamond_effective_log_dir: '{{diamond_effective_data_dir}}/logs'

diamond_collector_conf_extension: .conf
diamond_collector_conf_dir: /etc/diamond/collectors
diamond_collector_dir: /usr/share/diamond/collectors

diamond_common_role_tasks_config:
  role: diamond
  supported_distributions:
    - 'Debian'
  user: diamond
  paths:
    - '{{diamond_effective_data_dir}}'
    - '{{diamond_effective_log_dir}}'
    - {state: link, path: '{{diamond_log_dir}}', source: '{{diamond_effective_log_dir}}'}
    - '{{diamond_collector_conf_dir}}'
    - /etc/diamond
  packages:
    - diamond
    - python-requests
  notifications:
    - reload diamond
  port_configs: []
  services:
    - diamond
  monitoring_checks:
    - {command: 'python', argument: '/usr/bin/diamond'}

diamond_metric_proxy_hosts_ssh: []
diamond_metric_proxy_hosts_jetdirect: []
diamond_custom_collectors:
    - JetDirect
    - Log
    - ModdedHttpd
    - ProxyBulkFile
    - ProxyCPU
    - ProxyLoadAverage
    - ProxyMemory
    - ProxyNetwork
diamond_custom_collector_configs:
    - DiskUsage
