- name: '{{common_role_tasks_start_parent_role}}: Drop-out for unsupported distributions'
  fail: msg="Unsupported distribution '{{qhost_distribution}}' in '{{common_role_tasks_start_parent_role}}' role. Supported are {{common_role_tasks_start_config['supported_distributions'] | default([])}}"
  when: "qhost_distribution not in (common_role_tasks_start_config['supported_distributions'] | default([]))"

- name: '{{common_role_tasks_start_parent_role}}: Create service group'
  group:
    name: "{{common_role_tasks_start_config['group'] | default(common_role_tasks_start_config['user']) }}"
    state: present
    system: yes
  when: "common_role_tasks_start_config['group'] | default(common_role_tasks_start_config['user']) != 'omit'"

- name: '{{common_role_tasks_start_parent_role}}: Create service user'
  user:
    name: "{{common_role_tasks_start_config['user']}}"
    state: present
    comment: "Service user for {{common_role_tasks_start_config['role']}}"
    group: "{{common_role_tasks_start_config['group'] | default(common_role_tasks_start_config['user']) | replace_omit_string(omit)}}"
    groups: "{{common_role_tasks_start_config['extra_groups'] | default([]) | reject('equalto', '') | join(',')}}"
    home: "/var/lib/{{common_role_tasks_start_config['role']}}"
    create_home: no
    shell: /usr/sbin/nologin
    password: '!'
    system: yes
  when: "common_role_tasks_start_config['user'] != 'omit'"

- name: '{{common_role_tasks_start_parent_role}}: Create paths'
  file:
    state: "{{item['state'] | default('directory')}}"
    path: "{{item['path'] | default(item)}}"
    src: "{{item['source'] | default(omit)}}"
    owner: "{{common_role_tasks_start_config['user'] | replace_omit_string(omit)}}"
    group: "{{common_role_tasks_start_config['group'] | default(common_role_tasks_start_config['user']) | replace_omit_string(omit)}}"
    force: "{{item['force'] | default(False)}}"
    mode: "{{item['mode'] | default(0755 if (item['state'] | default('directory')) == 'directory' else (omit if ((item['state'] | default('directory')) == 'link') else 0444))}}"
  with_items: "{{common_role_tasks_start_config['paths']}}"
  notify: "{{common_role_tasks_start_config['notifications']}}"
