# qa:lint:distribution-independent
# qa:lint:no-log-level-needed

- name: 'Add libraries dashboard'
  set_fact:
    dashboards: "{{dashboards + ['Libraries' | dashboard_libraries]}}"
  changed_when: False
  tags:
    - always
