# qa:lint:distribution-independent
# lint:no-logging-needed

- name: 'Add libraries dashboard'
  set_fact:
    dashboards: "{{dashboards + ['Libraries' | dashboard_libraries]}}"
  changed_when: False
  tags:
    - always
