- name: Drop-out for unsupported distributions
  fail: msg="Unsupported distribution '{{ansible_distribution}}' in '{{role_path|basename}}' role"
  when: 'ansible_distribution not in ["Debian"]'

- name: Install ssh server packages
  apt:
    name: openssh-server
    state: present

- name: Create ssh server config
  template:
    dest: '/etc/ssh/sshd_config'
    src: 'sshd_config.j2'
    owner: root
    group: root
    mode: 0444
  notify:
    - restart sshd

- name: Updating port config
  set_fact:
    firewall_late_port_config: '{{firewall_late_port_config | default({}) | update_dict({
      ssh_server_port: {
        "name": "SSH",
        "protocol": "tcp",
        "incoming_net_accesses": ssh_server_net_accesses,
      }
    }, merge_lists=True)}}'
  changed_when: False
  tags:
    - always
